/* 
 * This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; version 2 of the License.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 */

package be.okno.tik.tak.commons.model;

import java.util.ArrayList;
import java.util.List;

public class MetaDataValueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mdval
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mdval
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mdval
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mdval
     *
     * @mbggenerated
     */
    public MetaDataValueExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mdval
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mdval
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mdval
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mdval
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mdval
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mdval
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mdval
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mdval
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mdval
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mdval
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mdval
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdMddefIsNull() {
            addCriterion("id_mddef is null");
            return (Criteria) this;
        }

        public Criteria andIdMddefIsNotNull() {
            addCriterion("id_mddef is not null");
            return (Criteria) this;
        }

        public Criteria andIdMddefEqualTo(Integer value) {
            addCriterion("id_mddef =", value, "idMddef");
            return (Criteria) this;
        }

        public Criteria andIdMddefNotEqualTo(Integer value) {
            addCriterion("id_mddef <>", value, "idMddef");
            return (Criteria) this;
        }

        public Criteria andIdMddefGreaterThan(Integer value) {
            addCriterion("id_mddef >", value, "idMddef");
            return (Criteria) this;
        }

        public Criteria andIdMddefGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_mddef >=", value, "idMddef");
            return (Criteria) this;
        }

        public Criteria andIdMddefLessThan(Integer value) {
            addCriterion("id_mddef <", value, "idMddef");
            return (Criteria) this;
        }

        public Criteria andIdMddefLessThanOrEqualTo(Integer value) {
            addCriterion("id_mddef <=", value, "idMddef");
            return (Criteria) this;
        }

        public Criteria andIdMddefIn(List<Integer> values) {
            addCriterion("id_mddef in", values, "idMddef");
            return (Criteria) this;
        }

        public Criteria andIdMddefNotIn(List<Integer> values) {
            addCriterion("id_mddef not in", values, "idMddef");
            return (Criteria) this;
        }

        public Criteria andIdMddefBetween(Integer value1, Integer value2) {
            addCriterion("id_mddef between", value1, value2, "idMddef");
            return (Criteria) this;
        }

        public Criteria andIdMddefNotBetween(Integer value1, Integer value2) {
            addCriterion("id_mddef not between", value1, value2, "idMddef");
            return (Criteria) this;
        }

        public Criteria andIdMdvalIsNull() {
            addCriterion("id_mdval is null");
            return (Criteria) this;
        }

        public Criteria andIdMdvalIsNotNull() {
            addCriterion("id_mdval is not null");
            return (Criteria) this;
        }

        public Criteria andIdMdvalEqualTo(Long value) {
            addCriterion("id_mdval =", value, "idMdval");
            return (Criteria) this;
        }

        public Criteria andIdMdvalNotEqualTo(Long value) {
            addCriterion("id_mdval <>", value, "idMdval");
            return (Criteria) this;
        }

        public Criteria andIdMdvalGreaterThan(Long value) {
            addCriterion("id_mdval >", value, "idMdval");
            return (Criteria) this;
        }

        public Criteria andIdMdvalGreaterThanOrEqualTo(Long value) {
            addCriterion("id_mdval >=", value, "idMdval");
            return (Criteria) this;
        }

        public Criteria andIdMdvalLessThan(Long value) {
            addCriterion("id_mdval <", value, "idMdval");
            return (Criteria) this;
        }

        public Criteria andIdMdvalLessThanOrEqualTo(Long value) {
            addCriterion("id_mdval <=", value, "idMdval");
            return (Criteria) this;
        }

        public Criteria andIdMdvalIn(List<Long> values) {
            addCriterion("id_mdval in", values, "idMdval");
            return (Criteria) this;
        }

        public Criteria andIdMdvalNotIn(List<Long> values) {
            addCriterion("id_mdval not in", values, "idMdval");
            return (Criteria) this;
        }

        public Criteria andIdMdvalBetween(Long value1, Long value2) {
            addCriterion("id_mdval between", value1, value2, "idMdval");
            return (Criteria) this;
        }

        public Criteria andIdMdvalNotBetween(Long value1, Long value2) {
            addCriterion("id_mdval not between", value1, value2, "idMdval");
            return (Criteria) this;
        }

        public Criteria andIdTikIsNull() {
            addCriterion("id_tik is null");
            return (Criteria) this;
        }

        public Criteria andIdTikIsNotNull() {
            addCriterion("id_tik is not null");
            return (Criteria) this;
        }

        public Criteria andIdTikEqualTo(Long value) {
            addCriterion("id_tik =", value, "idTik");
            return (Criteria) this;
        }

        public Criteria andIdTikNotEqualTo(Long value) {
            addCriterion("id_tik <>", value, "idTik");
            return (Criteria) this;
        }

        public Criteria andIdTikGreaterThan(Long value) {
            addCriterion("id_tik >", value, "idTik");
            return (Criteria) this;
        }

        public Criteria andIdTikGreaterThanOrEqualTo(Long value) {
            addCriterion("id_tik >=", value, "idTik");
            return (Criteria) this;
        }

        public Criteria andIdTikLessThan(Long value) {
            addCriterion("id_tik <", value, "idTik");
            return (Criteria) this;
        }

        public Criteria andIdTikLessThanOrEqualTo(Long value) {
            addCriterion("id_tik <=", value, "idTik");
            return (Criteria) this;
        }

        public Criteria andIdTikIn(List<Long> values) {
            addCriterion("id_tik in", values, "idTik");
            return (Criteria) this;
        }

        public Criteria andIdTikNotIn(List<Long> values) {
            addCriterion("id_tik not in", values, "idTik");
            return (Criteria) this;
        }

        public Criteria andIdTikBetween(Long value1, Long value2) {
            addCriterion("id_tik between", value1, value2, "idTik");
            return (Criteria) this;
        }

        public Criteria andIdTikNotBetween(Long value1, Long value2) {
            addCriterion("id_tik not between", value1, value2, "idTik");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mdval
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mdval
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}