/* 
 * This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; version 2 of the License.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 */

package be.okno.tik.tak.commons.model;

public class MetaDataValue {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mdval.id_mddef
	 * @mbggenerated
	 */
	private Integer idMddef;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mdval.id_mdval
	 * @mbggenerated
	 */
	private Long idMdval;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mdval.id_tik
	 * @mbggenerated
	 */
	private Long idTik;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mdval.value
	 * @mbggenerated
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mdval.id_mddef
	 * @return  the value of mdval.id_mddef
	 * @mbggenerated
	 */
	public Integer getIdMddef() {
		return idMddef;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mdval.id_mddef
	 * @param idMddef  the value for mdval.id_mddef
	 * @mbggenerated
	 */
	public void setIdMddef(Integer idMddef) {
		this.idMddef = idMddef;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mdval.id_mdval
	 * @return  the value of mdval.id_mdval
	 * @mbggenerated
	 */
	public Long getIdMdval() {
		return idMdval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mdval.id_mdval
	 * @param idMdval  the value for mdval.id_mdval
	 * @mbggenerated
	 */
	public void setIdMdval(Long idMdval) {
		this.idMdval = idMdval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mdval.id_tik
	 * @return  the value of mdval.id_tik
	 * @mbggenerated
	 */
	public Long getIdTik() {
		return idTik;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mdval.id_tik
	 * @param idTik  the value for mdval.id_tik
	 * @mbggenerated
	 */
	public void setIdTik(Long idTik) {
		this.idTik = idTik;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mdval.value
	 * @return  the value of mdval.value
	 * @mbggenerated
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mdval.value
	 * @param value  the value for mdval.value
	 * @mbggenerated
	 */
	public void setValue(String value) {
		this.value = value;
	}
}