/* 
 * This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; version 2 of the License.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 */

package be.okno.tik.tak.commons.model;

public class RelClockMetaDataDefinition {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column clock2mddef.id_clock
	 * @mbggenerated
	 */
	private Integer idClock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column clock2mddef.id_mddef
	 * @mbggenerated
	 */
	private Integer idMddef;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clock2mddef.id_clock
	 * @return  the value of clock2mddef.id_clock
	 * @mbggenerated
	 */
	public Integer getIdClock() {
		return idClock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clock2mddef.id_clock
	 * @param idClock  the value for clock2mddef.id_clock
	 * @mbggenerated
	 */
	public void setIdClock(Integer idClock) {
		this.idClock = idClock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clock2mddef.id_mddef
	 * @return  the value of clock2mddef.id_mddef
	 * @mbggenerated
	 */
	public Integer getIdMddef() {
		return idMddef;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clock2mddef.id_mddef
	 * @param idMddef  the value for clock2mddef.id_mddef
	 * @mbggenerated
	 */
	public void setIdMddef(Integer idMddef) {
		this.idMddef = idMddef;
	}
}