/* 
 * This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; version 2 of the License.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 */

package be.okno.tik.tak.commons.model;

import java.util.Set;

public class Tik {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tik.id_tik
	 * @mbggenerated
	 */
	private Long idTik;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tik.id_clock
	 * @mbggenerated
	 */
	private Integer idClock;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tik.id_tik
	 * @return  the value of tik.id_tik
	 * @mbggenerated
	 */
	public Long getIdTik() {
		return idTik;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tik.id_tik
	 * @param idTik  the value for tik.id_tik
	 * @mbggenerated
	 */
	public void setIdTik(Long idTik) {
		this.idTik = idTik;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tik.id_clock
	 * @return  the value of tik.id_clock
	 * @mbggenerated
	 */
	public Integer getIdClock() {
		return idClock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tik.id_clock
	 * @param idClock  the value for tik.id_clock
	 * @mbggenerated
	 */
	public void setIdClock(Integer idClock) {
		this.idClock = idClock;
	}

	private Set<MetaDataValue> metaDataValues;

	public void setMetaDataValues(Set<MetaDataValue> metaDataValues) {
		this.metaDataValues = metaDataValues;
	}

	public Set<MetaDataValue> getMetaDataValues() {
		return metaDataValues;
	}
}