/* 
 * This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; version 2 of the License.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 */

package be.okno.tik.tak.dao.mapper;

import be.okno.tik.tak.commons.model.MetaDataDefinition;

public interface MetaDataDefinitionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mddef
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer idMddef);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mddef
	 * @mbggenerated
	 */
	int insert(MetaDataDefinition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mddef
	 * @mbggenerated
	 */
	int insertSelective(MetaDataDefinition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mddef
	 * @mbggenerated
	 */
	MetaDataDefinition selectByPrimaryKey(Integer idMddef);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mddef
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(MetaDataDefinition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mddef
	 * @mbggenerated
	 */
	int updateByPrimaryKey(MetaDataDefinition record);
}