
/* 
 * This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; version 2 of the License.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 */

package be.okno.tik.tak.dao.mapper;

import be.okno.tik.tak.commons.model.Tik;

public interface TikMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tik
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long idTik);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tik
	 * @mbggenerated
	 */
	int insert(Tik record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tik
	 * @mbggenerated
	 */
	int insertSelective(Tik record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tik
	 * @mbggenerated
	 */
	Tik selectByPrimaryKey(Long idTik);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tik
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Tik record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tik
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Tik record);

	int insertWithIdClock(Tik record);
}